{% set name = "pytweening" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytweening-{{ version }}.tar.gz
  sha256: 767134f1bf57b76c1ce9f692dd1cfc776d9a279de6724e8d04854508fd7ededb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - pytweening
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/pytweening
  summary: A collection of tweening / easing functions.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jschueller
    - thewchan
