{% set name = "pytweening" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytweening-{{ version }}.tar.gz
  sha256: 0d8e14af529dd816ad4aa4a86757dfb5fe2fc2897e06f5db60183706a9370828

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - pytweening
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/pytweening
  summary: A collection of tweening / easing functions.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jschueller
    - thewchan
